"""Generate adversarial ZIP fixtures for the v0.5.1 dogfood plan §X4.3-X4.7.

Each function produces one synthetic ZIP that targets a specific corner case
of the importer / ``import_zip`` / ``list_zips`` path. The fixtures land in
the same directory as this script so they can be checked into version
control alongside the generator.

Run from the repo root:

    python tests/fixtures/adversarial/generate.py

The script is deterministic — the output bytes are identical across runs
(no timestamps land in the ZIP central directory's mtime field by default,
because :func:`zipfile.ZipFile.writestr` uses the ``ZipInfo`` it builds
from the constant strings below). The only file whose on-disk mtime
matters is ``x4-6-future-mtime.zip``; the script stamps that one with
``os.utime`` AFTER closing the ZIP, so it is the contributor's on-disk
mtime that is interesting, not the central-directory entries inside.

These fixtures are intended for **manual dogfood** by the human reviewer
(see ``internal/dogfood/v0-5-1-test-plan.md`` §X4). They are NOT pulled in by
``tests/`` because the importer's adversarial tests exercise their own
inline ZIPs.
"""

from __future__ import annotations

import os
import shutil
import zipfile
from pathlib import Path

# All output ZIPs live alongside this script.
OUT_DIR = Path(__file__).resolve().parent

# The minimum payload an Apple-Health-flavoured export ZIP needs for the
# importer's ``is_apple_health`` probe. Keeping the locale stub minimal
# keeps the fixtures small and reviewer-readable.
_TRIVIAL_EXPORT_XML = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<HealthData locale="en_US">'
    '<ExportDate value="2024-06-01 12:00:00 +0000"/>'
    "</HealthData>"
)

# A real Apple Health export always nests under ``apple_health_export/``;
# we mirror that path so the importer's marker check passes on the
# fixtures that need it.
_NESTED_XML_NAME = "apple_health_export/export.xml"


def _writestr(zip_path: Path, *entries: tuple[str, str | bytes]) -> None:
    """Build a ZIP at ``zip_path`` containing the given (name, payload) pairs.

    A tiny wrapper over :class:`zipfile.ZipFile` so each fixture builder
    below reads as a one-liner.
    """
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, payload in entries:
            data = payload.encode("utf-8") if isinstance(payload, str) else payload
            zf.writestr(name, data)


def make_x4_3_multi_entry_zero_byte_xml() -> Path:
    """§X4.3: multi-entry ZIP whose ``export.xml`` is 0 bytes.

    The importer should complete (no crash) but produce ``record_count=0``.
    A second, harmless entry is included so the ZIP isn't merely a single
    empty file — that's covered by §X4.1.
    """
    out = OUT_DIR / "x4-3-multi-empty-xml.zip"
    _writestr(
        out,
        (_NESTED_XML_NAME, ""),  # zero-byte payload, marker path satisfied
        ("apple_health_export/extra.txt", "harmless second entry"),
    )
    return out


def make_x4_4_zip_slip() -> Path:
    """§X4.4: zip-slip attempt — an entry whose name escapes the extract root.

    The importer's ``extract_zip_and_import`` MUST refuse to write the
    escape path (or sanitise it). The fixture also includes a valid
    Apple Health marker so the importer reaches the extraction step
    rather than failing at the ``is_apple_health`` probe.

    The escape path uses POSIX ``../`` segments; on Windows the
    importer should similarly refuse. Reviewer verifies that no file
    appears at ``/tmp/zip-slip-escape.txt`` (POSIX) or the equivalent
    parent-of-cwd location (Windows) after attempting the import.
    """
    out = OUT_DIR / "x4-4-zip-slip.zip"
    _writestr(
        out,
        ("../../../tmp/zip-slip-escape.txt", "malicious payload, should never be written"),
        (_NESTED_XML_NAME, _TRIVIAL_EXPORT_XML),
    )
    return out


def make_x4_5_duplicate_sha_pair() -> tuple[Path, Path]:
    """§X4.5: two ZIPs whose bytes are identical (so sha256 matches).

    Generated by writing one ZIP and copying it to a second filename;
    the second ZIP is byte-for-byte identical and therefore shares the
    sha256. ``list_zips`` should surface both with the same ``id``
    (= sha256[:8]); importing one of them should mark the other
    ``imported: true`` on the next ``list_zips`` call (= sha cache
    hit by the second filename).
    """
    primary = OUT_DIR / "x4-5-original.zip"
    _writestr(primary, (_NESTED_XML_NAME, _TRIVIAL_EXPORT_XML))
    clone = OUT_DIR / "x4-5-renamed-clone.zip"
    shutil.copy2(primary, clone)
    return primary, clone


# Far-future mtime used for §X4.6. 4102444800 == 2100-01-01 00:00:00 UTC.
# Far enough out that no plausible production user has produced an export
# with this mtime, but well within the int range Python's ``os.utime``
# accepts on every supported platform.
_FUTURE_MTIME_EPOCH = 4_102_444_800


def make_x4_6_future_mtime() -> Path:
    """§X4.6: ZIP whose on-disk mtime is in the year 2100.

    The fixture is a valid Apple Health ZIP; the only adversarial bit
    is the on-disk mtime. ``list_zips`` reports mtime via ISO string,
    and the sha cache keyed on ``(size, mtime)`` should treat this
    entry like any other (= the year is not validated). The fixture
    surfaces any future-date assertion the importer might grow.
    """
    out = OUT_DIR / "x4-6-future-mtime.zip"
    _writestr(out, (_NESTED_XML_NAME, _TRIVIAL_EXPORT_XML))
    os.utime(out, (_FUTURE_MTIME_EPOCH, _FUTURE_MTIME_EPOCH))
    return out


# An intentionally broken export.xml that the importer's Phase-1 XML
# parser must reject. The unclosed ``<Record`` tag triggers an
# ``lxml.etree.XMLSyntaxError`` partway through parsing, which the
# orchestrator catches and surfaces as a typed ``run_import_failed``
# envelope rather than a raw stack trace.
_BROKEN_XML = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<HealthData locale="en_US">'
    '<ExportDate value="2024-06-01 12:00:00 +0000"/>'
    '<Record type="HKQuantityTypeIdentifierHeartRate" value="72"'
    # No closing ``/>`` and no ``</HealthData>``. lxml is forgiving on
    # the start of the file but eventually fails the well-formedness
    # check, which is the signal the importer is supposed to handle
    # gracefully (= typed envelope, not crash).
)


def make_x4_7_broken_xml() -> Path:
    """§X4.7: ZIP whose ``export.xml`` is XML-syntax-invalid.

    The importer should advance to Phase-1, fail XML parse, and land
    the job in a terminal ``error`` state with a typed envelope.
    """
    out = OUT_DIR / "x4-7-broken-xml.zip"
    _writestr(out, (_NESTED_XML_NAME, _BROKEN_XML))
    return out


def main() -> None:
    """Regenerate every fixture in place. Idempotent."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    generated = [
        make_x4_3_multi_entry_zero_byte_xml(),
        make_x4_4_zip_slip(),
        *make_x4_5_duplicate_sha_pair(),
        make_x4_6_future_mtime(),
        make_x4_7_broken_xml(),
    ]
    for path in generated:
        print(f"wrote {path.relative_to(OUT_DIR.parent.parent.parent)}")


if __name__ == "__main__":
    main()
